const mongoose = require("mongoose");

/**
 * we create a data schema that contains the desired fields for each Sauce,
 * indicates their type and their character
 * No need to put a field for the Id since
 * it is automatically generated by Mongoose
 */
const sauceSchema = new mongoose.Schema({
  userId: { type: String},
  name: { type: String, required: true },
  manufacturer: { type: String, required: true },
  description: { type: String, required: true },
  mainPepper: { type: String, required: true },
  imageUrl: { type: String },
  heat: { type: Number },
  likes: { type: Number },
  dislikes: { type: Number },
  usersLiked: [String],
  usersDisliked: [String],
});

module.exports = mongoose.model("Sauce", sauceSchema);
