const mongoose = require('mongoose');

/**
 * we create a data schema that contains the desired fields for each Sauce,
 * indicates their type and their character
 * No need to put a field for the Id since
 * it is automatically generated by Mongoose 
 */
const sauceSchema = new mongoose.Schema({
    name: String,
    manufacturer: String,
    description: String,
    mainPepper: String,
    imageUrl: String,
    heat: Number,
    likes: Number,
    dislikes: Number,
    usersLiked: [String],
    usersDisliked: [String],
});

module.exports = mongoose.model('Sauce', sauceSchema);